name: Build and Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: make test
  nits:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Nits
      run: make nits
